[package]
name = "pycoforge"
version = "0.1.0"
edition = "2021"

[lib]
name = "pycoforge"
crate-type = ["cdylib"]

[dependencies]
mycoforge = { version='*', git='https://github.com/kpindur/mycoforge.git' }
pyo3 = "0.23.4"


